product-name: aws-services
network-properties:
  singleton_availability_zone:
    name: ((AZ_1))
  other_availability_zones:
  - name: ((AZ_1))
  - name: ((AZ_2))
  - name: ((AZ_3))
  network:
    name: pas
product-properties:
  .properties.aws_access_key_id:
    value: ((AWS_ACCESS_KEY_ID))
  .properties.aws_secret_access_key:
    value:
      secret: ((AWS_SECRET_ACCESS_KEY))
  .properties.backing_db_selector:
    value: Pivotal MySQL (v2)
  .properties.backing_db_selector.p_mysql.plan_name:
    value: db-small
  .properties.backing_db_selector.p_mysql.service_instance_name:
    value: aws-services
  .properties.db_ssl_selector:
    value: Disabled
errand-config:
resource-config:

