product-name: p-rabbitmq
network-properties:
  singleton_availability_zone:
    name: ((AZ_1))
  other_availability_zones:
  - name: ((AZ_1))
  - name: ((AZ_2))
  - name: ((AZ_3))
  network:
    name: pas
  service_network:
    name: services
product-properties:
  .rabbitmq-server.server_admin_credentials:
    value:
      identity: admin
      password: password
  .rabbitmq-server.rsa_certificate:
    value: 
      cert_pem: |
        ((DOMAIN_CRT))
      private_key_pem: |
        ((DOMAIN_KEY))
  .properties.disk_alarm_threshold:
    value: mem_relative_1_0
  .properties.syslog_selector:
    value: disabled
  .properties.on_demand_broker_plan_1_rabbitmq_az_placement:
    type: service_network_az_multi_select
    value:
    - ((AZ_1))
  .properties.on_demand_broker_plan_1_disk_limit_acknowledgement:
    type: multi_select_options
    value:
    - acknowledge
  .properties.on_demand_broker_plan_6_rabbitmq_az_placement:
    type: service_network_az_multi_select
    value:
    - ((AZ_1))
  .properties.on_demand_broker_plan_6_disk_limit_acknowledgement:
    value:
    - acknowledge
errand-config:
  on-demand-broker-smoke-tests:
    post-deploy-state: false
  upgrade-all-service-instances:
    post-deploy-state: false
resource-config:
  rabbitmq-server:
    instances: 1
